# 프로젝트명 및 DB 설정
spring:
  port: 8080
  application:
    name: EnjoyTrip
  datasource:
    url : jdbc:mysql://127.0.0.1:3306/logintest?serverTimezone=UTC
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ssafy
      password: ssafy
  profiles:
    include:
      - jwt
      - oauth
      
# MyBatis 설정
mybatis:
  type-aliases-package: com.ssafy.enjoytrip.doamin.**
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true